name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar dependencias
        run: npm install

      - name: Generar Android Nativo
        run: npx expo prebuild --platform android

      - name: Compilar APK con Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Release-APK
          path: android/app/build/outputs/apk/release/app-release.apk


